sources:
 
  - name: graph-network
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet
 
  - name: token-distribution
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/token-distribution
    transforms:
      - autoPagination:
          validateSchema: true

documents:
  - ops/queries/network.graphql
  - ops/queries/tokenLockWallets.graphql
  - ops/queries/curators.graphql